import express from 'express';
import cors from 'cors';
import connectDB from './config/db.js';
import vehicleRoutes from './routes/vehicleRoutes.js';
import appraisalRoutes from './routes/appraisalRoutes.js';
import auctionRoutes from './routes/auctionRoutes.js';
import bidRoutes from './routes/bidRoutes.js';
import paymentRoutes from './routes/paymentRoutes.js';
import transferRoutes from './routes/transferRoutes.js';
import dotenv from 'dotenv';
dotenv.config();
connectDB();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/vehicles', vehicleRoutes);
app.use('/api/appraisals', appraisalRoutes);
app.use('/api/auctions', auctionRoutes);
app.use('/api/bids', bidRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/transfers', transferRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=> console.log(`Server ${PORT}`));
